### ISSUE TITLE
Compiling with GCC 4.7 / Centos-6

### ISSUE THREAD

**Issue by ikrabbe** [mono/boringssl#2]
I want to try the mono master branch on a centos6 System and I installed the GCC-4.7.4 from the centos devtoolset-1.1 to be able to compile that at all.

This works when I set the /usr/bin/cc link to the devtoolset-1.1 location and set some environment variables.

But GCC-4.7 does not support `alignas`, so the crypto/poly1305 Test fails. With a little change, this does work anyway. So this is just a note for deprecated systems:

```
diff --git a/crypto/poly1305/poly1305_test.cc b/crypto/poly1305/poly1305_test.cc
index cae30a4..b126af5 100644
--- a/crypto/poly1305/poly1305_test.cc
+++ b/crypto/poly1305/poly1305_test.cc
@@ -41,7 +41,7 @@ static bool TestPoly1305(FileTest *t, void *arg) {
   CRYPTO_poly1305_init(&state, key.data());
   CRYPTO_poly1305_update(&state, in.data(), in.size());
   // |CRYPTO_poly1305_finish| requires a 16-byte-aligned output.
-  alignas(16) uint8_t out[16];
+  uint8_t out[16] __attribute__ ((aligned(0x10)));
   CRYPTO_poly1305_finish(&state, out);
   if (!t->ExpectBytesEqual(out, 16, mac.data(), mac.size())) {
     t->PrintLine("Single-shot Poly1305 failed.");
```

**Comment by directhex** [comment]
Can you repeat that in the form of a pull request?

**Comment by ikrabbe** [comment]
I thought I better should not, because it only targets a very old system.

**Comment by directhex** [comment]
You'd think, but our build farm uses Debian 7 a lot for x86, and that's also on GCC 4.7

**Comment by akoeplinger** [comment]
I pushed a commit that makes building the tests off by default, which should fix this and similar issues in a more general way: 2bc26c2772ad0a5d6b0ad4ba2ec77c8183d8932d

Thanks!
