### ISSUE TITLE
Running test suite

### ISSUE THREAD

**Issue by NattyNarwhal** [mono/boringssl#7]
I'm trying to debug an issue I'm having porting BoringSSL/TLS to ppc64, but I'd like to run the test suite to determine where problems could be precisely. I have go and ninja installed per BoringSSL upstream's instructions in `BUILDING.md`, but the tests won't run because they aren't build. Because of Mono integrating BTLS into its build system and the quirks that manifest as a result, what should be done if as a developer, I wanted to run BoringSSL tests?

**Comment by akoeplinger** [comment]
We disabled the tests in our fork with https://github.com/mono/boringssl/commit/2bc26c2772ad0a5d6b0ad4ba2ec77c8183d8932d, see if setting ENABLE_TESTS in cmake works.

**Comment by NattyNarwhal** [comment]
Ahhh, I see. You can't use the Ninja/Go based test runners though, you'll have to run the tests manually from the `mono/btls/build-shared` artifacts directory.

I also know what cipher is broken now though.... if I can't figure out how soonish, I'll file an issue. Cheers!
